FROM ubuntu

RUN apt-get update && apt-get install -y postgresql postgresql-client postgresql-contrib

USER postgres

RUN /etc/init.d/postgresql start &&\
    psql --command "CREATE USER docker WITH SUPERUSER PASSWORD 'docker';"

RUN echo "host all all 127.0.0.1 md5" >> /etc/postgresql/10/main/pg_hba.conf

RUN echo "listen_addresses='*'" >> /etc/postgresql/10/main/postgresql.conf

EXPOSE 5432

VOLUME ["etc/postgresql","/var/log/postgresql", 
