"""empty message

Revision ID: 4cde6ac56ec2
Revises: 1d02224950ad
Create Date: 2019-12-20 14:25:55.168626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cde6ac56ec2'
down_revision = '1d02224950ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_group_table_groupname', table_name='group_table')
    op.create_index(op.f('ix_group_table_groupname'), 'group_table', ['groupname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_table_groupname'), table_name='group_table')
    op.create_index('ix_group_table_groupname', 'group_table', ['groupname'], unique=True)
    # ### end Alembic commands ###
