"""empty message

Revision ID: 7627c4298a83
Revises: 
Create Date: 2019-12-28 10:42:46.085959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7627c4298a83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_table_email'), 'user_table', ['email'], unique=True)
    op.create_index(op.f('ix_user_table_username'), 'user_table', ['username'], unique=True)
    op.create_table('group_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=50), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('group_description', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_table_group_description'), 'group_table', ['group_description'], unique=False)
    op.create_index(op.f('ix_group_table_groupname'), 'group_table', ['groupname'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('member_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_table.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['member_name'], ['user_table.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('message_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['user_table.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_group_table_groupname'), table_name='group_table')
    op.drop_index(op.f('ix_group_table_group_description'), table_name='group_table')
    op.drop_table('group_table')
    op.drop_index(op.f('ix_user_table_username'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_email'), table_name='user_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
